version: "3.8"

services:
  web:
    build: .
    image: christin_web
    container_name: christin_web
    ports:
      - 5004:5000
    command: flask run --host 0.0.0.0
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - FLASK_DEBUG=0
      - CHRISTIN_MYSQL_HOST=host.docker.internal
      - APP_SETTINGS=config.production.ProductionConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CHRISTIN_REDIS_HOST=redis
      - CHRISTIN_NEO_HOST=host.docker.internal
    depends_on:
      - redis

  worker:
    build: .
    command: celery worker --app=application.server.tasks.celery --loglevel=info --logfile=logs/celery.log
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - FLASK_DEBUG=0
      - APP_SETTINGS=config.production.ProductionConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CHRISTIN_REDIS_HOST=redis
      - CHRISTIN_NEO_HOST=host.docker.internal
    depends_on:
      - web
      - redis

  dashboard:
    build: .
    command: flower --app=application.server.tasks.celery --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5556:5555
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=config.production.ProductionConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - worker

  redis:
    image: redis:6-alpine
    container_name: christin_redis
    ports:
      - 6379:6379
